# Site settings
title: Super Kartoffel
# email: your-email@domain.com
# description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/kartoffel"
url: "http://filtercake.github.io"
twitter_username: filtercake
github_username:  filtercake
flickr_username:  filtercake
permalink: title

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  sourcemap: true